var a = 2;
var b = 1;
document.write("<br />a = "+a);
document.write("<br />b = "+b);      
var result = --a - --b + ++b + b--;
document.write("<br />--a - --b + ++b + b-- = <br />a = "+a);
document.write("<br />b = "+b);
document.write("<br />result = "+result);
result = --a;
document.write("<br />--a = <br />a = "+a);
document.write("<br />b = "+b);
document.write("<br />result = "+result);
result = --a - --b;
document.write("<br />--a - --b = <br />a = "+a);
document.write("<br />b = "+b);
document.write("<br />result = "+result);
result = --a - --b + ++b;
document.write("<br />--a - --b + ++b = <br />a = "+a);
document.write("<br />b = "+b);
document.write("<br />result = "+result);
result = --a - --b + ++b + b--;
document.write("<br />--a - --b + ++b + b-- = <br />a = "+a);
document.write("<br />b = "+b);
document.write("<br />result = "+result);
